name: Docker Build

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_images:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  

      # - name: Build mios Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: |
      #       ghcr.io/chipclee/robot-sim:${{ github.sha }}
      #       ghcr.io/chipclee/robot-sim:main

      - name: Build mios Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./build
          file: ./build/Dockerfile
          push: true
          tags: |
            ghcr.io/chipclee/libfranka:${{ github.sha }}
            ghcr.io/chipclee/libfranka:main

      